### ISSUE TITLE
Document how .changed() method can be used with watch task

### ISSUE THREAD

**Issue by nalbion** [steida/gulp-closure-deps#6]
Please document how .changed() method can be used with watch task, providing an example

**Comment by steida** [comment]
Code is documentation :-) https://github.com/steida/gulp-este/search?utf8=%E2%9C%93&q=changed

**Comment by steida** [comment]
You can send PR ofc ;-)

**Comment by nalbion** [comment]
Would be great if you could cut & paste a few lines from one of your projects' gulpfile into the README to show how you use it. 

     On Friday, 30 January 2015, 1:57, Daniel Steigerwald <notifications@github.com> wrote:
   

 You can send PR ofc ;-)—
